# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Us
    url: about_us
    weight: 10
  - name: Team Members
    url: team_members
    weight: 20
  - name: Research Projects & Grants
    url: research
    weight: 30
  - name: News
    url: news
    weight: 40
  - name: Resources
    url: resources
    weight: 50
  - name: Publications
    url: publication
    weight: 60
  - name: Contact
    url: contact
    weight: 70
